### ISSUE TITLE
Is it possible to get this working with null ls ? 

### ISSUE THREAD

**Issue by vsedov** [joechrisellis/lsp-format-modifications.nvim#1]
Kinda curious, cause this would be really usefull if it could work with null ls . 
Though if im honest i was really sure how one would set it up properly.

**Comment by joechrisellis** [comment]
Hello -- yep, it's totally possible to have this work with [null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim). In your call to `require"null-ls".setup(...)`, you'll want to supply an `on_attach` function -- [check out the null-ls.nvim docs for `on_attach` here](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/4f2b231e41c52cf51a51c3683635d9e72117b5c4/doc/CONFIG.md#on_attach-function-optional).

It will probably look something like this:

```lua
local null_ls = require"null-ls"
null_ls.setup({
  sources = {
    -- NOTE: sources must support range formatting!
    null_ls.builtins.formatting.prettier,
    null_ls.builtins.formatting.autopep8,
    -- ...
  },
  on_attach = function(client, bufnr)
    -- your usual configuration — options, keymaps, etc
    -- ...
  
    local lsp_format_modifications = require"lsp-format-modifications"
    lsp_format_modifications.attach(client, bufnr, { format_on_save = false })
  end
})
```

The caveat here is that the sources must support range formatting. At the time of writing, from a cursory glance over the null-ls's built-in sources, it looks like the following support range formatting:
- `autopep8`
- `clang_format`
- `prettier_d_slim`
- `prettier`
- `stylua`
- `yapf`

Hope this helps!

**Comment by vsedov** [comment]
Ah epic, thanks, also great plugin :)
