### ISSUE TITLE
None VCS project idea

### ISSUE THREAD

**Issue by ZerGo0** [joechrisellis/lsp-format-modifications.nvim#5]
I made a pretty long reddit comment and thought that it would probably be better to put it here.

I think that a local history would be a pretty good alternative for non VCS projects. There is a existing nvim plugin: https://github.com/dinhhuy258/vim-local-history (there hasn't been a commit for a 2 years now, not sure if it still works or not.)

It uses pythons built-in difflib: https://github.com/dinhhuy258/vim-local-history/blob/000b8acecd14ff005a4e1198c82be901c7fbe904/rplugin/python3/local-history/utils.py#L46

https://docs.python.org/3/library/difflib.html

I think that it should be possible to use the plugin to detect the diff and use the same behavior that is currently in place. This should probably only be used as fallback if there is no VCS in place tho.

What do you think?

**Comment by joechrisellis** [comment]
I am not sure about this. I'm not convinced that enough people share this problem to justify solving it. 🤔 

The situation described -- formatting modifications in a project that doesn't use revision control -- just feels quite niche. I think a better course of action in this instance would be to start using a VCS. Projects not using revision control are few and far between, and the main motivator that drove the creation of this plugin in the first place was avoiding diff noise from using formatters globally in legacy projects.

I can probably be swayed if there is a broader, more compelling use case for this functionality, but right now I'm not seeing it. 😓
